export const CREATE_DOG = 'CREATE_DOG'
export const GET_DOGS = 'GET_DOGS'
export const GET_NAME= 'GET_NAME'
export const FILTER = 'FILTER'
export const FILTER_BD_API = 'FILTER_BD_API'
export const ORDER = 'ORDER'
export const ORDER_PESOS = 'ORDER_PESOS'
export const TEMPERAMENTO ='TEMPERAMENTO'