export const GET_DOGS = 'GET_DOGS'
export const GET_NAME= 'GET_NAME'
export const CREATE_DOG = 'CREATE_DOG'
export const ORDER = 'ORDER'
export const FILTER = 'FILTER'
export const TEMPERAMENTO ='TEMPERAMENTO'